gboolean    (*GtkTreeSelectionFunc)         (GtkTreeSelection *selection,GtkTreeModel *model,GtkTreePath *path,gboolean path_currently_selected,gpointer data);
void        (*GtkTreeSelectionForeachFunc)  (GtkTreeModel *model,GtkTreePath *path,GtkTreeIter *iter,gpointer data);
void        gtk_tree_selection_set_mode     (GtkTreeSelection *selection,GtkSelectionMode type);
GtkSelectionMode gtk_tree_selection_get_mode(GtkTreeSelection *selection);
void        gtk_tree_selection_set_select_function(GtkTreeSelection *selection,GtkTreeSelectionFunc func,gpointer data,GtkDestroyNotify destroy);
gpointer    gtk_tree_selection_get_user_data(GtkTreeSelection *selection);
GtkTreeView* gtk_tree_selection_get_tree_view(GtkTreeSelection *selection);
gboolean    gtk_tree_selection_get_selected (GtkTreeSelection *selection,GtkTreeModel **model,GtkTreeIter *iter);
void        gtk_tree_selection_selected_foreach(GtkTreeSelection *selection,GtkTreeSelectionForeachFunc func,gpointer data);
GList*      gtk_tree_selection_get_selected_rows(GtkTreeSelection *selection,GtkTreeModel **model);
gint        gtk_tree_selection_count_selected_rows(GtkTreeSelection *selection);
void        gtk_tree_selection_select_path  (GtkTreeSelection *selection,GtkTreePath *path);
void        gtk_tree_selection_unselect_path(GtkTreeSelection *selection,GtkTreePath *path);
gboolean    gtk_tree_selection_path_is_selected(GtkTreeSelection *selection,GtkTreePath *path);
void        gtk_tree_selection_select_iter  (GtkTreeSelection *selection,GtkTreeIter *iter);
void        gtk_tree_selection_unselect_iter(GtkTreeSelection *selection,GtkTreeIter *iter);
gboolean    gtk_tree_selection_iter_is_selected(GtkTreeSelection *selection,GtkTreeIter *iter);
void        gtk_tree_selection_select_all   (GtkTreeSelection *selection);
void        gtk_tree_selection_unselect_all (GtkTreeSelection *selection);
void        gtk_tree_selection_select_range (GtkTreeSelection *selection,GtkTreePath *start_path,GtkTreePath *end_path);
void        gtk_tree_selection_unselect_range(GtkTreeSelection *selection,GtkTreePath *start_path,GtkTreePath *end_path);
