GtkWidget*  gtk_color_button_new            (void);
GtkWidget*  gtk_color_button_new_with_color (const GdkColor *color);
void        gtk_color_button_set_color      (GtkColorButton *color_button,const GdkColor *color);
void        gtk_color_button_get_color      (GtkColorButton *color_button,GdkColor *color);
void        gtk_color_button_set_alpha      (GtkColorButton *color_button,guint16 alpha);
guint16     gtk_color_button_get_alpha      (GtkColorButton *color_button);
void        gtk_color_button_set_use_alpha  (GtkColorButton *color_button,gboolean use_alpha);
gboolean    gtk_color_button_get_use_alpha  (GtkColorButton *color_button);
void        gtk_color_button_set_title      (GtkColorButton *color_button,const gchar *title);
const gchar* gtk_color_button_get_title     (GtkColorButton *color_button);
