GtkWidget*  gtk_cell_view_new               (void);
GtkWidget*  gtk_cell_view_new_with_text     (const gchar *text);
GtkWidget*  gtk_cell_view_new_with_markup   (const gchar *markup);
GtkWidget*  gtk_cell_view_new_with_pixbuf   (GdkPixbuf *pixbuf);
void        gtk_cell_view_set_model         (GtkCellView *cell_view,GtkTreeModel *model);
void        gtk_cell_view_set_displayed_row (GtkCellView *cell_view,GtkTreePath *path);
GtkTreePath* gtk_cell_view_get_displayed_row(GtkCellView *cell_view);
gboolean    gtk_cell_view_get_size_of_row   (GtkCellView *cell_view,GtkTreePath *path,GtkRequisition *requisition);
void        gtk_cell_view_set_background_color(GtkCellView *cell_view,const GdkColor *color);
GList*      gtk_cell_view_get_cell_renderers(GtkCellView *cell_view);
