void        gtk_progress_set_show_text      (GtkProgress *progress,gboolean show_text);
void        gtk_progress_set_text_alignment (GtkProgress *progress,gfloat x_align,gfloat y_align);
void        gtk_progress_set_format_string  (GtkProgress *progress,const gchar *format);
void        gtk_progress_set_adjustment     (GtkProgress *progress,GtkAdjustment *adjustment);
void        gtk_progress_set_percentage     (GtkProgress *progress,gdouble percentage);
void        gtk_progress_set_value          (GtkProgress *progress,gdouble value);
gdouble     gtk_progress_get_value          (GtkProgress *progress);
void        gtk_progress_set_activity_mode  (GtkProgress *progress,gboolean activity_mode);
gchar*      gtk_progress_get_current_text   (GtkProgress *progress);
gchar*      gtk_progress_get_text_from_value(GtkProgress *progress,gdouble value);
gdouble     gtk_progress_get_current_percentage(GtkProgress *progress);
gdouble     gtk_progress_get_percentage_from_value(GtkProgress *progress,gdouble value);
void        gtk_progress_configure          (GtkProgress *progress,gdouble value,gdouble min,gdouble max);
