GtkWidget*  gtk_scrolled_window_new         (GtkAdjustment *hadjustment,GtkAdjustment *vadjustment);
GtkAdjustment* gtk_scrolled_window_get_hadjustment(GtkScrolledWindow *scrolled_window);
GtkAdjustment* gtk_scrolled_window_get_vadjustment(GtkScrolledWindow *scrolled_window);
GtkWidget*  gtk_scrolled_window_get_hscrollbar(GtkScrolledWindow *scrolled_window);
GtkWidget*  gtk_scrolled_window_get_vscrollbar(GtkScrolledWindow *scrolled_window);
void        gtk_scrolled_window_set_policy  (GtkScrolledWindow *scrolled_window,GtkPolicyType hscrollbar_policy,GtkPolicyType vscrollbar_policy);
void        gtk_scrolled_window_add_with_viewport(GtkScrolledWindow *scrolled_window,GtkWidget *child);
void        gtk_scrolled_window_set_placement(GtkScrolledWindow *scrolled_window,GtkCornerType window_placement);
void        gtk_scrolled_window_set_shadow_type(GtkScrolledWindow *scrolled_window,GtkShadowType type);
void        gtk_scrolled_window_set_hadjustment(GtkScrolledWindow *scrolled_window,GtkAdjustment *hadjustment);
void        gtk_scrolled_window_set_vadjustment(GtkScrolledWindow *scrolled_window,GtkAdjustment *vadjustment);
GtkCornerType gtk_scrolled_window_get_placement(GtkScrolledWindow *scrolled_window);
void        gtk_scrolled_window_get_policy  (GtkScrolledWindow *scrolled_window,GtkPolicyType *hscrollbar_policy,GtkPolicyType *vscrollbar_policy);
GtkShadowType gtk_scrolled_window_get_shadow_type(GtkScrolledWindow *scrolled_window);
