void        (*GtkCallback)                  (GtkWidget *widget,gpointer data);
struct      GtkAllocation;
GtkWidget*  gtk_widget_new                  (GType type,const gchar *first_property_name,...);
GtkWidget*  gtk_widget_ref                  (GtkWidget *widget);
void        gtk_widget_unref                (GtkWidget *widget);
void        gtk_widget_destroy              (GtkWidget *widget);
void        gtk_widget_destroyed            (GtkWidget *widget,GtkWidget **widget_pointer);
void        gtk_widget_set                  (GtkWidget *widget,const gchar *first_property_name,...);
void        gtk_widget_unparent             (GtkWidget *widget);
void        gtk_widget_show                 (GtkWidget *widget);
void        gtk_widget_show_now             (GtkWidget *widget);
void        gtk_widget_hide                 (GtkWidget *widget);
void        gtk_widget_show_all             (GtkWidget *widget);
void        gtk_widget_hide_all             (GtkWidget *widget);
void        gtk_widget_map                  (GtkWidget *widget);
void        gtk_widget_unmap                (GtkWidget *widget);
void        gtk_widget_realize              (GtkWidget *widget);
void        gtk_widget_unrealize            (GtkWidget *widget);
void        gtk_widget_queue_draw           (GtkWidget *widget);
void        gtk_widget_queue_resize         (GtkWidget *widget);
void        gtk_widget_queue_resize_no_redraw(GtkWidget *widget);
void        gtk_widget_draw                 (GtkWidget *widget,GdkRectangle *area);
void        gtk_widget_size_request         (GtkWidget *widget,GtkRequisition *requisition);
void        gtk_widget_get_child_requisition(GtkWidget *widget,GtkRequisition *requisition);
void        gtk_widget_size_allocate        (GtkWidget *widget,GtkAllocation *allocation);
void        gtk_widget_add_accelerator      (GtkWidget *widget,const gchar *accel_signal,GtkAccelGroup *accel_group,guint accel_key,GdkModifierType accel_mods,GtkAccelFlags accel_flags);
gboolean    gtk_widget_remove_accelerator   (GtkWidget *widget,GtkAccelGroup *accel_group,guint accel_key,GdkModifierType accel_mods);
void        gtk_widget_set_accel_path       (GtkWidget *widget,const gchar *accel_path,GtkAccelGroup *accel_group);
GList*      gtk_widget_list_accel_closures  (GtkWidget *widget);
gboolean    gtk_widget_can_activate_accel   (GtkWidget *widget,guint signal_id);
gboolean    gtk_widget_event                (GtkWidget *widget,GdkEvent *event);
gboolean    gtk_widget_activate             (GtkWidget *widget);
void        gtk_widget_reparent             (GtkWidget *widget,GtkWidget *new_parent);
gboolean    gtk_widget_intersect            (GtkWidget *widget,GdkRectangle *area,GdkRectangle *intersection);
gboolean    gtk_widget_is_focus             (GtkWidget *widget);
void        gtk_widget_grab_focus           (GtkWidget *widget);
void        gtk_widget_grab_default         (GtkWidget *widget);
void        gtk_widget_set_name             (GtkWidget *widget,const gchar *name);
const gchar* gtk_widget_get_name            (GtkWidget *widget);
void        gtk_widget_set_state            (GtkWidget *widget,GtkStateType state);
void        gtk_widget_set_sensitive        (GtkWidget *widget,gboolean sensitive);
void        gtk_widget_set_parent           (GtkWidget *widget,GtkWidget *parent);
void        gtk_widget_set_parent_window    (GtkWidget *widget,GdkWindow *parent_window);
GdkWindow*  gtk_widget_get_parent_window    (GtkWidget *widget);
void        gtk_widget_set_uposition        (GtkWidget *widget,gint x,gint y);
void        gtk_widget_set_usize            (GtkWidget *widget,gint width,gint height);
void        gtk_widget_set_events           (GtkWidget *widget,gint events);
void        gtk_widget_add_events           (GtkWidget *widget,gint events);
void        gtk_widget_set_extension_events (GtkWidget *widget,GdkExtensionMode mode);
GdkExtensionMode gtk_widget_get_extension_events(GtkWidget *widget);
GtkWidget*  gtk_widget_get_toplevel         (GtkWidget *widget);
GtkWidget*  gtk_widget_get_ancestor         (GtkWidget *widget,GType widget_type);
GdkColormap* gtk_widget_get_colormap        (GtkWidget *widget);
void        gtk_widget_set_colormap         (GtkWidget *widget,GdkColormap *colormap);
GdkVisual*  gtk_widget_get_visual           (GtkWidget *widget);
gint        gtk_widget_get_events           (GtkWidget *widget);
void        gtk_widget_get_pointer          (GtkWidget *widget,gint *x,gint *y);
gboolean    gtk_widget_is_ancestor          (GtkWidget *widget,GtkWidget *ancestor);
gboolean    gtk_widget_translate_coordinates(GtkWidget *src_widget,GtkWidget *dest_widget,gint src_x,gint src_y,gint *dest_x,gint *dest_y);
gboolean    gtk_widget_hide_on_delete       (GtkWidget *widget);
void        gtk_widget_set_style            (GtkWidget *widget,GtkStyle *style);
void        gtk_widget_ensure_style         (GtkWidget *widget);
GtkStyle*   gtk_widget_get_style            (GtkWidget *widget);
void        gtk_widget_reset_rc_styles      (GtkWidget *widget);
void        gtk_widget_push_colormap        (GdkColormap *cmap);
void        gtk_widget_pop_colormap         (void);
void        gtk_widget_set_default_colormap (GdkColormap *colormap);
GtkStyle*   gtk_widget_get_default_style    (void);
GdkColormap* gtk_widget_get_default_colormap(void);
GdkVisual*  gtk_widget_get_default_visual   (void);
void        gtk_widget_set_direction        (GtkWidget *widget,GtkTextDirection dir);
GtkTextDirection gtk_widget_get_direction   (GtkWidget *widget);
void        gtk_widget_set_default_direction(GtkTextDirection dir);
GtkTextDirection gtk_widget_get_default_direction(void);
void        gtk_widget_shape_combine_mask   (GtkWidget *widget,GdkBitmap *shape_mask,gint offset_x,gint offset_y);
void        gtk_widget_path                 (GtkWidget *widget,guint *path_length,gchar **path,gchar **path_reversed);
void        gtk_widget_class_path           (GtkWidget *widget,guint *path_length,gchar **path,gchar **path_reversed);
gchar*      gtk_widget_get_composite_name   (GtkWidget *widget);
void        gtk_widget_modify_style         (GtkWidget *widget,GtkRcStyle *style);
GtkRcStyle* gtk_widget_get_modifier_style   (GtkWidget *widget);
void        gtk_widget_modify_fg            (GtkWidget *widget,GtkStateType state,const GdkColor *color);
void        gtk_widget_modify_bg            (GtkWidget *widget,GtkStateType state,const GdkColor *color);
void        gtk_widget_modify_text          (GtkWidget *widget,GtkStateType state,const GdkColor *color);
void        gtk_widget_modify_base          (GtkWidget *widget,GtkStateType state,const GdkColor *color);
void        gtk_widget_modify_font          (GtkWidget *widget,PangoFontDescription *font_desc);
PangoContext* gtk_widget_create_pango_context(GtkWidget *widget);
PangoContext* gtk_widget_get_pango_context  (GtkWidget *widget);
PangoLayout* gtk_widget_create_pango_layout (GtkWidget *widget,const gchar *text);
GdkPixbuf*  gtk_widget_render_icon          (GtkWidget *widget,const gchar *stock_id,GtkIconSize size,const gchar *detail);
void        gtk_widget_pop_composite_child  (void);
void        gtk_widget_push_composite_child (void);
void        gtk_widget_queue_clear          (GtkWidget *widget);
void        gtk_widget_queue_clear_area     (GtkWidget *widget,gint x,gint y,gint width,gint height);
void        gtk_widget_queue_draw_area      (GtkWidget *widget,gint x,gint y,gint width,gint height);
void        gtk_widget_reset_shapes         (GtkWidget *widget);
void        gtk_widget_set_app_paintable    (GtkWidget *widget,gboolean app_paintable);
void        gtk_widget_set_double_buffered  (GtkWidget *widget,gboolean double_buffered);
void        gtk_widget_set_redraw_on_allocate(GtkWidget *widget,gboolean redraw_on_allocate);
void        gtk_widget_set_composite_name   (GtkWidget *widget,const gchar *name);
gboolean    gtk_widget_set_scroll_adjustments(GtkWidget *widget,GtkAdjustment *hadjustment,GtkAdjustment *vadjustment);
gboolean    gtk_widget_mnemonic_activate    (GtkWidget *widget,gboolean group_cycling);
void        gtk_widget_class_install_style_property(GtkWidgetClass *klass,GParamSpec *pspec);
void        gtk_widget_class_install_style_property_parser(GtkWidgetClass *klass,GParamSpec *pspec,GtkRcPropertyParser parser);
GParamSpec* gtk_widget_class_find_style_property(GtkWidgetClass *klass,const gchar *property_name);
GParamSpec** gtk_widget_class_list_style_properties(GtkWidgetClass *klass,guint *n_properties);
GdkRegion*  gtk_widget_region_intersect     (GtkWidget *widget,GdkRegion *region);
gint        gtk_widget_send_expose          (GtkWidget *widget,GdkEvent *event);
void        gtk_widget_style_get            (GtkWidget *widget,const gchar *first_property_name,...);
void        gtk_widget_style_get_property   (GtkWidget *widget,const gchar *property_name,GValue *value);
void        gtk_widget_style_get_valist     (GtkWidget *widget,const gchar *first_property_name,va_list var_args);
AtkObject*  gtk_widget_get_accessible       (GtkWidget *widget);
gboolean    gtk_widget_child_focus          (GtkWidget *widget,GtkDirectionType direction);
void        gtk_widget_child_notify         (GtkWidget *widget,const gchar *child_property);
void        gtk_widget_freeze_child_notify  (GtkWidget *widget);
gboolean    gtk_widget_get_child_visible    (GtkWidget *widget);
GtkWidget*  gtk_widget_get_parent           (GtkWidget *widget);
GtkSettings* gtk_widget_get_settings        (GtkWidget *widget);
GtkClipboard* gtk_widget_get_clipboard      (GtkWidget *widget,GdkAtom selection);
GdkDisplay* gtk_widget_get_display          (GtkWidget *widget);
GdkWindow*  gtk_widget_get_root_window      (GtkWidget *widget);
GdkScreen*  gtk_widget_get_screen           (GtkWidget *widget);
gboolean    gtk_widget_has_screen           (GtkWidget *widget);
void        gtk_widget_get_size_request     (GtkWidget *widget,gint *width,gint *height);
void        gtk_widget_set_child_visible    (GtkWidget *widget,gboolean is_visible);
void        gtk_widget_set_size_request     (GtkWidget *widget,gint width,gint height);
void        gtk_widget_thaw_child_notify    (GtkWidget *widget);
void        gtk_widget_set_no_show_all      (GtkWidget *widget,gboolean no_show_all);
gboolean    gtk_widget_get_no_show_all      (GtkWidget *widget);
GList*      gtk_widget_list_mnemonic_labels (GtkWidget *widget);
void        gtk_widget_add_mnemonic_label   (GtkWidget *widget,GtkWidget *label);
void        gtk_widget_remove_mnemonic_label(GtkWidget *widget,GtkWidget *label);
GtkRequisition* gtk_requisition_copy        (const GtkRequisition *requisition);
void        gtk_requisition_free            (GtkRequisition *requisition);
