void        gtk_image_get_icon_set          (GtkImage *image,GtkIconSet **icon_set,GtkIconSize *size);
void        gtk_image_get_image             (GtkImage *image,GdkImage **gdk_image,GdkBitmap **mask);
GdkPixbuf*  gtk_image_get_pixbuf            (GtkImage *image);
void        gtk_image_get_pixmap            (GtkImage *image,GdkPixmap **pixmap,GdkBitmap **mask);
void        gtk_image_get_stock             (GtkImage *image,gchar **stock_id,GtkIconSize *size);
GdkPixbufAnimation* gtk_image_get_animation (GtkImage *image);
void        gtk_image_get_icon_name         (GtkImage *image,G_CONST_RETURN gchar **icon_name,GtkIconSize *size);
GtkImageType gtk_image_get_storage_type     (GtkImage *image);
GtkWidget*  gtk_image_new_from_file         (const gchar *filename);
GtkWidget*  gtk_image_new_from_icon_set     (GtkIconSet *icon_set,GtkIconSize size);
GtkWidget*  gtk_image_new_from_image        (GdkImage *image,GdkBitmap *mask);
GtkWidget*  gtk_image_new_from_pixbuf       (GdkPixbuf *pixbuf);
GtkWidget*  gtk_image_new_from_pixmap       (GdkPixmap *pixmap,GdkBitmap *mask);
GtkWidget*  gtk_image_new_from_stock        (const gchar *stock_id,GtkIconSize size);
GtkWidget*  gtk_image_new_from_animation    (GdkPixbufAnimation *animation);
GtkWidget*  gtk_image_new_from_icon_name    (const gchar *icon_name,GtkIconSize size);
void        gtk_image_set_from_file         (GtkImage *image,const gchar *filename);
void        gtk_image_set_from_icon_set     (GtkImage *image,GtkIconSet *icon_set,GtkIconSize size);
void        gtk_image_set_from_image        (GtkImage *image,GdkImage *gdk_image,GdkBitmap *mask);
void        gtk_image_set_from_pixbuf       (GtkImage *image,GdkPixbuf *pixbuf);
void        gtk_image_set_from_pixmap       (GtkImage *image,GdkPixmap *pixmap,GdkBitmap *mask);
void        gtk_image_set_from_stock        (GtkImage *image,const gchar *stock_id,GtkIconSize size);
void        gtk_image_set_from_animation    (GtkImage *image,GdkPixbufAnimation *animation);
void        gtk_image_set_from_icon_name    (GtkImage *image,const gchar *icon_name,GtkIconSize size);
void        gtk_image_clear                 (GtkImage *image);
GtkWidget*  gtk_image_new                   (void);
void        gtk_image_set                   (GtkImage *image,GdkImage *val,GdkBitmap *mask);
void        gtk_image_get                   (GtkImage *image,GdkImage **val,GdkBitmap **mask);
void        gtk_image_set_pixel_size        (GtkImage *image,gint pixel_size);
gint        gtk_image_get_pixel_size        (GtkImage *image);
