GtkWidget*  gtk_table_new                   (guint rows,guint columns,gboolean homogeneous);
void        gtk_table_resize                (GtkTable *table,guint rows,guint columns);
void        gtk_table_attach                (GtkTable *table,GtkWidget *child,guint left_attach,guint right_attach,guint top_attach,guint bottom_attach,GtkAttachOptions xoptions,GtkAttachOptions yoptions,guint xpadding,guint ypadding);
void        gtk_table_attach_defaults       (GtkTable *table,GtkWidget *widget,guint left_attach,guint right_attach,guint top_attach,guint bottom_attach);
void        gtk_table_set_row_spacing       (GtkTable *table,guint row,guint spacing);
void        gtk_table_set_col_spacing       (GtkTable *table,guint column,guint spacing);
void        gtk_table_set_row_spacings      (GtkTable *table,guint spacing);
void        gtk_table_set_col_spacings      (GtkTable *table,guint spacing);
void        gtk_table_set_homogeneous       (GtkTable *table,gboolean homogeneous);
guint       gtk_table_get_default_row_spacing(GtkTable *table);
gboolean    gtk_table_get_homogeneous       (GtkTable *table);
guint       gtk_table_get_row_spacing       (GtkTable *table,guint row);
guint       gtk_table_get_col_spacing       (GtkTable *table,guint column);
guint       gtk_table_get_default_col_spacing(GtkTable *table);
