gboolean    (*GtkTreeViewColumnDropFunc)    (GtkTreeView *tree_view,GtkTreeViewColumn *column,GtkTreeViewColumn *prev_column,GtkTreeViewColumn *next_column,gpointer data);
void        (*GtkTreeViewMappingFunc)       (GtkTreeView *tree_view,GtkTreePath *path,gpointer user_data);
gboolean    (*GtkTreeViewSearchEqualFunc)   (GtkTreeModel *model,gint column,const gchar *key,GtkTreeIter *iter,gpointer search_data);
GtkWidget*  gtk_tree_view_new               (void);
GtkWidget*  gtk_tree_view_new_with_model    (GtkTreeModel *model);
GtkTreeModel* gtk_tree_view_get_model       (GtkTreeView *tree_view);
void        gtk_tree_view_set_model         (GtkTreeView *tree_view,GtkTreeModel *model);
GtkTreeSelection* gtk_tree_view_get_selection(GtkTreeView *tree_view);
GtkAdjustment* gtk_tree_view_get_hadjustment(GtkTreeView *tree_view);
void        gtk_tree_view_set_hadjustment   (GtkTreeView *tree_view,GtkAdjustment *adjustment);
GtkAdjustment* gtk_tree_view_get_vadjustment(GtkTreeView *tree_view);
void        gtk_tree_view_set_vadjustment   (GtkTreeView *tree_view,GtkAdjustment *adjustment);
gboolean    gtk_tree_view_get_headers_visible(GtkTreeView *tree_view);
void        gtk_tree_view_set_headers_visible(GtkTreeView *tree_view,gboolean headers_visible);
void        gtk_tree_view_columns_autosize  (GtkTreeView *tree_view);
void        gtk_tree_view_set_headers_clickable(GtkTreeView *tree_view,gboolean setting);
void        gtk_tree_view_set_rules_hint    (GtkTreeView *tree_view,gboolean setting);
gboolean    gtk_tree_view_get_rules_hint    (GtkTreeView *tree_view);
gint        gtk_tree_view_append_column     (GtkTreeView *tree_view,GtkTreeViewColumn *column);
gint        gtk_tree_view_remove_column     (GtkTreeView *tree_view,GtkTreeViewColumn *column);
gint        gtk_tree_view_insert_column     (GtkTreeView *tree_view,GtkTreeViewColumn *column,gint position);
gint        gtk_tree_view_insert_column_with_attributes(GtkTreeView *tree_view,gint position,const gchar *title,GtkCellRenderer *cell,...);
gint        gtk_tree_view_insert_column_with_data_func(GtkTreeView *tree_view,gint position,const gchar *title,GtkCellRenderer *cell,GtkTreeCellDataFunc func,gpointer data,GDestroyNotify dnotify);
GtkTreeViewColumn* gtk_tree_view_get_column (GtkTreeView *tree_view,gint n);
GList*      gtk_tree_view_get_columns       (GtkTreeView *tree_view);
void        gtk_tree_view_move_column_after (GtkTreeView *tree_view,GtkTreeViewColumn *column,GtkTreeViewColumn *base_column);
void        gtk_tree_view_set_expander_column(GtkTreeView *tree_view,GtkTreeViewColumn *column);
GtkTreeViewColumn* gtk_tree_view_get_expander_column(GtkTreeView *tree_view);
void        gtk_tree_view_set_column_drag_function(GtkTreeView *tree_view,GtkTreeViewColumnDropFunc func,gpointer user_data,GtkDestroyNotify destroy);
void        gtk_tree_view_scroll_to_point   (GtkTreeView *tree_view,gint tree_x,gint tree_y);
void        gtk_tree_view_scroll_to_cell    (GtkTreeView *tree_view,GtkTreePath *path,GtkTreeViewColumn *column,gboolean use_align,gfloat row_align,gfloat col_align);
void        gtk_tree_view_set_cursor        (GtkTreeView *tree_view,GtkTreePath *path,GtkTreeViewColumn *focus_column,gboolean start_editing);
void        gtk_tree_view_set_cursor_on_cell(GtkTreeView *tree_view,GtkTreePath *path,GtkTreeViewColumn *focus_column,GtkCellRenderer *focus_cell,gboolean start_editing);
void        gtk_tree_view_get_cursor        (GtkTreeView *tree_view,GtkTreePath **path,GtkTreeViewColumn **focus_column);
void        gtk_tree_view_row_activated     (GtkTreeView *tree_view,GtkTreePath *path,GtkTreeViewColumn *column);
void        gtk_tree_view_expand_all        (GtkTreeView *tree_view);
void        gtk_tree_view_collapse_all      (GtkTreeView *tree_view);
void        gtk_tree_view_expand_to_path    (GtkTreeView *tree_view,GtkTreePath *path);
gboolean    gtk_tree_view_expand_row        (GtkTreeView *tree_view,GtkTreePath *path,gboolean open_all);
gboolean    gtk_tree_view_collapse_row      (GtkTreeView *tree_view,GtkTreePath *path);
void        gtk_tree_view_map_expanded_rows (GtkTreeView *tree_view,GtkTreeViewMappingFunc func,gpointer data);
gboolean    gtk_tree_view_row_expanded      (GtkTreeView *tree_view,GtkTreePath *path);
void        gtk_tree_view_set_reorderable   (GtkTreeView *tree_view,gboolean reorderable);
gboolean    gtk_tree_view_get_reorderable   (GtkTreeView *tree_view);
gboolean    gtk_tree_view_get_path_at_pos   (GtkTreeView *tree_view,gint x,gint y,GtkTreePath **path,GtkTreeViewColumn **column,gint *cell_x,gint *cell_y);
void        gtk_tree_view_get_cell_area     (GtkTreeView *tree_view,GtkTreePath *path,GtkTreeViewColumn *column,GdkRectangle *rect);
void        gtk_tree_view_get_background_area(GtkTreeView *tree_view,GtkTreePath *path,GtkTreeViewColumn *column,GdkRectangle *rect);
void        gtk_tree_view_get_visible_rect  (GtkTreeView *tree_view,GdkRectangle *visible_rect);
gboolean    gtk_tree_view_get_visible_range (GtkTreeView *tree_view,GtkTreePath **start_path,GtkTreePath **end_path);
GdkWindow*  gtk_tree_view_get_bin_window    (GtkTreeView *tree_view);
void        gtk_tree_view_widget_to_tree_coords(GtkTreeView *tree_view,gint wx,gint wy,gint *tx,gint *ty);
void        gtk_tree_view_tree_to_widget_coords(GtkTreeView *tree_view,gint tx,gint ty,gint *wx,gint *wy);
void        gtk_tree_view_enable_model_drag_dest(GtkTreeView *tree_view,const GtkTargetEntry *targets,gint n_targets,GdkDragAction actions);
void        gtk_tree_view_enable_model_drag_source(GtkTreeView *tree_view,GdkModifierType start_button_mask,const GtkTargetEntry *targets,gint n_targets,GdkDragAction actions);
void        gtk_tree_view_unset_rows_drag_source(GtkTreeView *tree_view);
void        gtk_tree_view_unset_rows_drag_dest(GtkTreeView *tree_view);
void        gtk_tree_view_set_drag_dest_row (GtkTreeView *tree_view,GtkTreePath *path,GtkTreeViewDropPosition pos);
void        gtk_tree_view_get_drag_dest_row (GtkTreeView *tree_view,GtkTreePath **path,GtkTreeViewDropPosition *pos);
gboolean    gtk_tree_view_get_dest_row_at_pos(GtkTreeView *tree_view,gint drag_x,gint drag_y,GtkTreePath **path,GtkTreeViewDropPosition *pos);
GdkPixmap*  gtk_tree_view_create_row_drag_icon(GtkTreeView *tree_view,GtkTreePath *path);
void        gtk_tree_view_set_enable_search (GtkTreeView *tree_view,gboolean enable_search);
gboolean    gtk_tree_view_get_enable_search (GtkTreeView *tree_view);
gint        gtk_tree_view_get_search_column (GtkTreeView *tree_view);
void        gtk_tree_view_set_search_column (GtkTreeView *tree_view,gint column);
GtkTreeViewSearchEqualFunc gtk_tree_view_get_search_equal_func(GtkTreeView *tree_view);
void        gtk_tree_view_set_search_equal_func(GtkTreeView *tree_view,GtkTreeViewSearchEqualFunc search_equal_func,gpointer search_user_data,GtkDestroyNotify search_destroy);
gboolean    gtk_tree_view_get_fixed_height_mode(GtkTreeView *tree_view);
void        gtk_tree_view_set_fixed_height_mode(GtkTreeView *tree_view,gboolean enable);
gboolean    gtk_tree_view_get_hover_selection(GtkTreeView *tree_view);
void        gtk_tree_view_set_hover_selection(GtkTreeView *tree_view,gboolean hover);
gboolean    gtk_tree_view_get_hover_expand  (GtkTreeView *tree_view);
void        gtk_tree_view_set_hover_expand  (GtkTreeView *tree_view,gboolean expand);
void        (*GtkTreeDestroyCountFunc)      (GtkTreeView *tree_view,GtkTreePath *path,gint children,gpointer user_data);
void        gtk_tree_view_set_destroy_count_func(GtkTreeView *tree_view,GtkTreeDestroyCountFunc func,gpointer data,GtkDestroyNotify destroy);
gboolean    (*GtkTreeViewRowSeparatorFunc)  (GtkTreeModel *model,GtkTreeIter *iter,gpointer data);
GtkTreeViewRowSeparatorFunc gtk_tree_view_get_row_separator_func(GtkTreeView *tree_view);
void        gtk_tree_view_set_row_separator_func(GtkTreeView *tree_view,GtkTreeViewRowSeparatorFunc func,gpointer data,GtkDestroyNotify destroy);
