GtkIconSource* gtk_icon_source_copy         (const GtkIconSource *source);
void        gtk_icon_source_free            (GtkIconSource *source);
void        gtk_icon_factory_add            (GtkIconFactory *factory,const gchar *stock_id,GtkIconSet *icon_set);
void        gtk_icon_factory_add_default    (GtkIconFactory *factory);
GtkIconSet* gtk_icon_factory_lookup         (GtkIconFactory *factory,const gchar *stock_id);
GtkIconSet* gtk_icon_factory_lookup_default (const gchar *stock_id);
GtkIconFactory* gtk_icon_factory_new        (void);
void        gtk_icon_factory_remove_default (GtkIconFactory *factory);
void        gtk_icon_set_add_source         (GtkIconSet *icon_set,const GtkIconSource *source);
GtkIconSet* gtk_icon_set_copy               (GtkIconSet *icon_set);
GtkIconSet* gtk_icon_set_new                (void);
GtkIconSet* gtk_icon_set_new_from_pixbuf    (GdkPixbuf *pixbuf);
GtkIconSet* gtk_icon_set_ref                (GtkIconSet *icon_set);
GdkPixbuf*  gtk_icon_set_render_icon        (GtkIconSet *icon_set,GtkStyle *style,GtkTextDirection direction,GtkStateType state,GtkIconSize size,GtkWidget *widget,const char *detail);
void        gtk_icon_set_unref              (GtkIconSet *icon_set);
gboolean    gtk_icon_size_lookup            (GtkIconSize size,gint *width,gint *height);
gboolean    gtk_icon_size_lookup_for_settings(GtkSettings *settings,GtkIconSize size,gint *width,gint *height);
GtkIconSize gtk_icon_size_register          (const gchar *name,gint width,gint height);
void        gtk_icon_size_register_alias    (const gchar *alias,GtkIconSize target);
GtkIconSize gtk_icon_size_from_name         (const gchar *name);
const gchar* gtk_icon_size_get_name         (GtkIconSize size);
void        gtk_icon_set_get_sizes          (GtkIconSet *icon_set,GtkIconSize **sizes,gint *n_sizes);
GtkTextDirection gtk_icon_source_get_direction(const GtkIconSource *source);
gboolean    gtk_icon_source_get_direction_wildcarded(const GtkIconSource *source);
const gchar* gtk_icon_source_get_filename   (const GtkIconSource *source);
GdkPixbuf*  gtk_icon_source_get_pixbuf      (const GtkIconSource *source);
const gchar* gtk_icon_source_get_icon_name  (const GtkIconSource *source);
GtkIconSize gtk_icon_source_get_size        (const GtkIconSource *source);
gboolean    gtk_icon_source_get_size_wildcarded(const GtkIconSource *source);
GtkStateType gtk_icon_source_get_state      (const GtkIconSource *source);
gboolean    gtk_icon_source_get_state_wildcarded(const GtkIconSource *source);
GtkIconSource* gtk_icon_source_new          (void);
void        gtk_icon_source_set_direction   (GtkIconSource *source,GtkTextDirection direction);
void        gtk_icon_source_set_direction_wildcarded(GtkIconSource *source,gboolean setting);
void        gtk_icon_source_set_filename    (GtkIconSource *source,const gchar *filename);
void        gtk_icon_source_set_pixbuf      (GtkIconSource *source,GdkPixbuf *pixbuf);
void        gtk_icon_source_set_icon_name   (GtkIconSource *source,const gchar *icon_name);
void        gtk_icon_source_set_size        (GtkIconSource *source,GtkIconSize size);
void        gtk_icon_source_set_size_wildcarded(GtkIconSource *source,gboolean setting);
void        gtk_icon_source_set_state       (GtkIconSource *source,GtkStateType state);
void        gtk_icon_source_set_state_wildcarded(GtkIconSource *source,gboolean setting);
