GtkWidget*  gtk_combo_box_new               (void);
GtkWidget*  gtk_combo_box_new_with_model    (GtkTreeModel *model);
gint        gtk_combo_box_get_wrap_width    (GtkComboBox *combo_box);
void        gtk_combo_box_set_wrap_width    (GtkComboBox *combo_box,gint width);
gint        gtk_combo_box_get_row_span_column(GtkComboBox *combo_box);
void        gtk_combo_box_set_row_span_column(GtkComboBox *combo_box,gint row_span);
gint        gtk_combo_box_get_column_span_column(GtkComboBox *combo_box);
void        gtk_combo_box_set_column_span_column(GtkComboBox *combo_box,gint column_span);
gint        gtk_combo_box_get_active        (GtkComboBox *combo_box);
void        gtk_combo_box_set_active        (GtkComboBox *combo_box,gint index_);
gboolean    gtk_combo_box_get_active_iter   (GtkComboBox *combo_box,GtkTreeIter *iter);
void        gtk_combo_box_set_active_iter   (GtkComboBox *combo_box,GtkTreeIter *iter);
GtkTreeModel* gtk_combo_box_get_model       (GtkComboBox *combo_box);
void        gtk_combo_box_set_model         (GtkComboBox *combo_box,GtkTreeModel *model);
GtkWidget*  gtk_combo_box_new_text          (void);
void        gtk_combo_box_append_text       (GtkComboBox *combo_box,const gchar *text);
void        gtk_combo_box_insert_text       (GtkComboBox *combo_box,gint position,const gchar *text);
void        gtk_combo_box_prepend_text      (GtkComboBox *combo_box,const gchar *text);
void        gtk_combo_box_remove_text       (GtkComboBox *combo_box,gint position);
gchar*      gtk_combo_box_get_active_text   (GtkComboBox *combo_box);
void        gtk_combo_box_popup             (GtkComboBox *combo_box);
void        gtk_combo_box_popdown           (GtkComboBox *combo_box);
AtkObject*  gtk_combo_box_get_popup_accessible(GtkComboBox *combo_box);
GtkTreeViewRowSeparatorFunc gtk_combo_box_get_row_separator_func(GtkComboBox *combo_box);
void        gtk_combo_box_set_row_separator_func(GtkComboBox *combo_box,GtkTreeViewRowSeparatorFunc func,gpointer data,GtkDestroyNotify destroy);
void        gtk_combo_box_set_add_tearoffs  (GtkComboBox *combo_box,gboolean add_tearoffs);
gboolean    gtk_combo_box_get_add_tearoffs  (GtkComboBox *combo_box);
void        gtk_combo_box_set_focus_on_click(GtkComboBox *combo,gboolean focus_on_click);
gboolean    gtk_combo_box_get_focus_on_click(GtkComboBox *combo);
