void        gtk_editable_select_region      (GtkEditable *editable,gint start,gint end);
gboolean    gtk_editable_get_selection_bounds(GtkEditable *editable,gint *start,gint *end);
void        gtk_editable_insert_text        (GtkEditable *editable,const gchar *new_text,gint new_text_length,gint *position);
void        gtk_editable_delete_text        (GtkEditable *editable,gint start_pos,gint end_pos);
gchar*      gtk_editable_get_chars          (GtkEditable *editable,gint start_pos,gint end_pos);
void        gtk_editable_cut_clipboard      (GtkEditable *editable);
void        gtk_editable_copy_clipboard     (GtkEditable *editable);
void        gtk_editable_paste_clipboard    (GtkEditable *editable);
void        gtk_editable_delete_selection   (GtkEditable *editable);
void        gtk_editable_set_position       (GtkEditable *editable,gint position);
gint        gtk_editable_get_position       (GtkEditable *editable);
void        gtk_editable_set_editable       (GtkEditable *editable,gboolean is_editable);
gboolean    gtk_editable_get_editable       (GtkEditable *editable);
