GtkWidget*  gtk_list_new                    (void);
void        gtk_list_insert_items           (GtkList *list,GList *items,gint position);
void        gtk_list_append_items           (GtkList *list,GList *items);
void        gtk_list_prepend_items          (GtkList *list,GList *items);
void        gtk_list_remove_items           (GtkList *list,GList *items);
void        gtk_list_remove_items_no_unref  (GtkList *list,GList *items);
void        gtk_list_clear_items            (GtkList *list,gint start,gint end);
void        gtk_list_select_item            (GtkList *list,gint item);
void        gtk_list_unselect_item          (GtkList *list,gint item);
void        gtk_list_select_child           (GtkList *list,GtkWidget *child);
void        gtk_list_unselect_child         (GtkList *list,GtkWidget *child);
gint        gtk_list_child_position         (GtkList *list,GtkWidget *child);
void        gtk_list_set_selection_mode     (GtkList *list,GtkSelectionMode mode);
void        gtk_list_extend_selection       (GtkList *list,GtkScrollType scroll_type,gfloat position,gboolean auto_start_selection);
void        gtk_list_start_selection        (GtkList *list);
void        gtk_list_end_selection          (GtkList *list);
void        gtk_list_select_all             (GtkList *list);
void        gtk_list_unselect_all           (GtkList *list);
void        gtk_list_scroll_horizontal      (GtkList *list,GtkScrollType scroll_type,gfloat position);
void        gtk_list_scroll_vertical        (GtkList *list,GtkScrollType scroll_type,gfloat position);
void        gtk_list_toggle_add_mode        (GtkList *list);
void        gtk_list_toggle_focus_row       (GtkList *list);
void        gtk_list_toggle_row             (GtkList *list,GtkWidget *item);
void        gtk_list_undo_selection         (GtkList *list);
void        gtk_list_end_drag_selection     (GtkList *list);
