GtkWidget*  gtk_notebook_new                (void);
gint        gtk_notebook_append_page        (GtkNotebook *notebook,GtkWidget *child,GtkWidget *tab_label);
gint        gtk_notebook_append_page_menu   (GtkNotebook *notebook,GtkWidget *child,GtkWidget *tab_label,GtkWidget *menu_label);
gint        gtk_notebook_prepend_page       (GtkNotebook *notebook,GtkWidget *child,GtkWidget *tab_label);
gint        gtk_notebook_prepend_page_menu  (GtkNotebook *notebook,GtkWidget *child,GtkWidget *tab_label,GtkWidget *menu_label);
gint        gtk_notebook_insert_page        (GtkNotebook *notebook,GtkWidget *child,GtkWidget *tab_label,gint position);
gint        gtk_notebook_insert_page_menu   (GtkNotebook *notebook,GtkWidget *child,GtkWidget *tab_label,GtkWidget *menu_label,gint position);
void        gtk_notebook_remove_page        (GtkNotebook *notebook,gint page_num);
gint        gtk_notebook_page_num           (GtkNotebook *notebook,GtkWidget *child);
void        gtk_notebook_next_page          (GtkNotebook *notebook);
void        gtk_notebook_prev_page          (GtkNotebook *notebook);
void        gtk_notebook_reorder_child      (GtkNotebook *notebook,GtkWidget *child,gint position);
void        gtk_notebook_set_tab_pos        (GtkNotebook *notebook,GtkPositionType pos);
void        gtk_notebook_set_show_tabs      (GtkNotebook *notebook,gboolean show_tabs);
void        gtk_notebook_set_show_border    (GtkNotebook *notebook,gboolean show_border);
void        gtk_notebook_set_scrollable     (GtkNotebook *notebook,gboolean scrollable);
void        gtk_notebook_set_tab_border     (GtkNotebook *notebook,guint border_width);
void        gtk_notebook_popup_enable       (GtkNotebook *notebook);
void        gtk_notebook_popup_disable      (GtkNotebook *notebook);
gint        gtk_notebook_get_current_page   (GtkNotebook *notebook);
GtkWidget*  gtk_notebook_get_menu_label     (GtkNotebook *notebook,GtkWidget *child);
GtkWidget*  gtk_notebook_get_nth_page       (GtkNotebook *notebook,gint page_num);
gint        gtk_notebook_get_n_pages        (GtkNotebook *notebook);
GtkWidget*  gtk_notebook_get_tab_label      (GtkNotebook *notebook,GtkWidget *child);
void        gtk_notebook_query_tab_label_packing(GtkNotebook *notebook,GtkWidget *child,gboolean *expand,gboolean *fill,GtkPackType *pack_type);
void        gtk_notebook_set_homogeneous_tabs(GtkNotebook *notebook,gboolean homogeneous);
void        gtk_notebook_set_menu_label     (GtkNotebook *notebook,GtkWidget *child,GtkWidget *menu_label);
void        gtk_notebook_set_menu_label_text(GtkNotebook *notebook,GtkWidget *child,const gchar *menu_text);
void        gtk_notebook_set_tab_hborder    (GtkNotebook *notebook,guint tab_hborder);
void        gtk_notebook_set_tab_label      (GtkNotebook *notebook,GtkWidget *child,GtkWidget *tab_label);
void        gtk_notebook_set_tab_label_packing(GtkNotebook *notebook,GtkWidget *child,gboolean expand,gboolean fill,GtkPackType pack_type);
void        gtk_notebook_set_tab_label_text (GtkNotebook *notebook,GtkWidget *child,const gchar *tab_text);
void        gtk_notebook_set_tab_vborder    (GtkNotebook *notebook,guint tab_vborder);
const gchar* gtk_notebook_get_menu_label_text(GtkNotebook *notebook,GtkWidget *child);
gboolean    gtk_notebook_get_scrollable     (GtkNotebook *notebook);
gboolean    gtk_notebook_get_show_border    (GtkNotebook *notebook);
gboolean    gtk_notebook_get_show_tabs      (GtkNotebook *notebook);
const gchar* gtk_notebook_get_tab_label_text(GtkNotebook *notebook,GtkWidget *child);
GtkPositionType gtk_notebook_get_tab_pos    (GtkNotebook *notebook);
void        gtk_notebook_set_current_page   (GtkNotebook *notebook,gint page_num);
