all:
	make all-recursive

all-recursive:
	make -Cde all

clean:
	make clean-recursive

clean-recursive:
	make -Cde clean

uninstall:
	make uninstall-recursive

uninstall-recursive:
	make -Cde uninstall

install:
	make install-recursive

install-recursive:
	make -Cde install
