Extern
	Function gtk_scrolled_window_new:Byte Ptr(hadjustment:Byte Ptr,vadjustment:Byte Ptr)="gtk_scrolled_window_new"
	Function gtk_scrolled_window_get_hadjustment:Byte Ptr(scrolled_window:Byte Ptr)="gtk_scrolled_window_get_hadjustment"
	Function gtk_scrolled_window_get_vadjustment:Byte Ptr(scrolled_window:Byte Ptr)="gtk_scrolled_window_get_vadjustment"
	Function gtk_scrolled_window_get_hscrollbar:Byte Ptr(scrolled_window:Byte Ptr)="gtk_scrolled_window_get_hscrollbar"
	Function gtk_scrolled_window_get_vscrollbar:Byte Ptr(scrolled_window:Byte Ptr)="gtk_scrolled_window_get_vscrollbar"
	Function gtk_scrolled_window_set_policy(scrolled_window:Byte Ptr,hscrollbar_policy:GtkPolicyType,vscrollbar_policy:GtkPolicyType)="gtk_scrolled_window_set_policy"
	Function gtk_scrolled_window_add_with_viewport(scrolled_window:Byte Ptr,child:Byte Ptr)="gtk_scrolled_window_add_with_viewport"
	Function gtk_scrolled_window_set_placement(scrolled_window:Byte Ptr,window_placement:GtkCornerType)="gtk_scrolled_window_set_placement"
	Function gtk_scrolled_window_set_shadow_type(scrolled_window:Byte Ptr,type:GtkShadowType)="gtk_scrolled_window_set_shadow_type"
	Function gtk_scrolled_window_set_hadjustment(scrolled_window:Byte Ptr,hadjustment:Byte Ptr)="gtk_scrolled_window_set_hadjustment"
	Function gtk_scrolled_window_set_vadjustment(scrolled_window:Byte Ptr,vadjustment:Byte Ptr)="gtk_scrolled_window_set_vadjustment"
	Function gtk_scrolled_window_get_placement:GtkCornerType(scrolled_window:Byte Ptr)="gtk_scrolled_window_get_placement"
	Function gtk_scrolled_window_get_policy(scrolled_window:Byte Ptr,hscrollbar_policy:Byte Ptr,vscrollbar_policy:Byte Ptr)="gtk_scrolled_window_get_policy"
	Function gtk_scrolled_window_get_shadow_type:GtkShadowType(scrolled_window:Byte Ptr)="gtk_scrolled_window_get_shadow_type"
End Extern
