GtkAction*  gtk_action_new                  (const gchar *name,const gchar *label,const gchar *tooltip,const gchar *stock_id);
const gchar* gtk_action_get_name            (GtkAction *action);
gboolean    gtk_action_is_sensitive         (GtkAction *action);
gboolean    gtk_action_get_sensitive        (GtkAction *action);
void        gtk_action_set_sensitive        (GtkAction *action,gboolean sensitive);
gboolean    gtk_action_is_visible           (GtkAction *action);
gboolean    gtk_action_get_visible          (GtkAction *action);
void        gtk_action_set_visible          (GtkAction *action,gboolean visible);
void        gtk_action_activate             (GtkAction *action);
GtkWidget*  gtk_action_create_icon          (GtkAction *action,GtkIconSize icon_size);
GtkWidget*  gtk_action_create_menu_item     (GtkAction *action);
GtkWidget*  gtk_action_create_tool_item     (GtkAction *action);
void        gtk_action_connect_proxy        (GtkAction *action,GtkWidget *proxy);
void        gtk_action_disconnect_proxy     (GtkAction *action,GtkWidget *proxy);
GSList*     gtk_action_get_proxies          (GtkAction *action);
void        gtk_action_connect_accelerator  (GtkAction *action);
void        gtk_action_disconnect_accelerator(GtkAction *action);
void        gtk_action_block_activate_from  (GtkAction *action,GtkWidget *proxy);
void        gtk_action_unblock_activate_from(GtkAction *action,GtkWidget *proxy);
const gchar* gtk_action_get_accel_path      (GtkAction *action);
void        gtk_action_set_accel_path       (GtkAction *action,const gchar *accel_path);
GClosure*   gtk_action_get_accel_closure    (GtkAction *action);
void        gtk_action_set_accel_group      (GtkAction *action,GtkAccelGroup *accel_group);
