GtkWidget*  gtk_color_selection_new         (void);
void        gtk_color_selection_set_update_policy(GtkColorSelection *colorsel,GtkUpdateType policy);
void        gtk_color_selection_set_has_opacity_control(GtkColorSelection *colorsel,gboolean has_opacity);
gboolean    gtk_color_selection_get_has_opacity_control(GtkColorSelection *colorsel);
void        gtk_color_selection_set_has_palette(GtkColorSelection *colorsel,gboolean has_palette);
gboolean    gtk_color_selection_get_has_palette(GtkColorSelection *colorsel);
guint16     gtk_color_selection_get_current_alpha(GtkColorSelection *colorsel);
void        gtk_color_selection_set_current_alpha(GtkColorSelection *colorsel,guint16 alpha);
void        gtk_color_selection_get_current_color(GtkColorSelection *colorsel,GdkColor *color);
void        gtk_color_selection_set_current_color(GtkColorSelection *colorsel,const GdkColor *color);
guint16     gtk_color_selection_get_previous_alpha(GtkColorSelection *colorsel);
void        gtk_color_selection_set_previous_alpha(GtkColorSelection *colorsel,guint16 alpha);
void        gtk_color_selection_get_previous_color(GtkColorSelection *colorsel,GdkColor *color);
void        gtk_color_selection_set_previous_color(GtkColorSelection *colorsel,const GdkColor *color);
gboolean    gtk_color_selection_is_adjusting(GtkColorSelection *colorsel);
gboolean    gtk_color_selection_palette_from_string(const gchar *str,GdkColor **colors,gint *n_colors);
gchar*      gtk_color_selection_palette_to_string(const GdkColor *colors,gint n_colors);
GtkColorSelectionChangePaletteFunc gtk_color_selection_set_change_palette_hook(GtkColorSelectionChangePaletteFunc func);
void        (*GtkColorSelectionChangePaletteFunc)(const GdkColor *colors,gint n_colors);
GtkColorSelectionChangePaletteWithScreenFunc gtk_color_selection_set_change_palette_with_screen_hook(GtkColorSelectionChangePaletteWithScreenFunc func);
void        (*GtkColorSelectionChangePaletteWithScreenFunc)(GdkScreen *screen,const GdkColor *colors,gint n_colors);
void        gtk_color_selection_set_color   (GtkColorSelection *colorsel,gdouble *color);
void        gtk_color_selection_get_color   (GtkColorSelection *colorsel,gdouble *color);
