#!/bin/sh
echo "Automated installer for BlitzMax module Pub.GTK"
echo "(C) 2005-2006 by phiker"
echo "install: Checking identity"
if [ $LOGNAME = "root" ]; then
        echo "install: Installing as root can potentially cause problems, please install as normal user"
        exit 1
fi
if [ $1 = "--configure-only" ]; then
        echo "install: Running in configuring mode, the other stupid things will be skipped"
else
        echo "install: Running in full mode"
        echo "install: Compiling Scintilla"
        make -Cscintilla/gtk
        retval=$?
        if [ $retval -ne 0 ]; then
                echo "install: make returned $retval, exiting"
                exit 1
        fi
fi
echo "install: Runnning perl config script"
./genconf
retval=$?
if [ $retval -ne 0 ]; then
        echo "install: genconf returned $retval, exiting"
        exit 1
fi
echo "install: Renaming files"
mv gtk.bmx gtk_old.bmx
retval=$?
if [ $retval -ne 0 ]; then
        echo "install: mv returned $retval, exiting"
        exit 1
fi
mv gtk_new.bmx gtk.bmx
retval=$?
if [ $retval -ne 0 ]; then
        echo "install: mv returned $retval, exiting"
        exit 1
fi
echo "install: Running bmk to make module"
../../../bin/bmk makemods pub.gtk
retval=$?
if [ $retval -ne 0 ]; then
        echo
        echo "install: bmk returned $retval, exiting"
        exit 1
fi
echo "install: Finished"
