GtkSettings* gtk_settings_get_default       (void);
GtkSettings* gtk_settings_get_for_screen    (GdkScreen *screen);
void        gtk_settings_install_property   (GParamSpec *pspec);
void        gtk_settings_install_property_parser(GParamSpec *pspec,GtkRcPropertyParser parser);
gboolean    gtk_rc_property_parse_color     (const GParamSpec *pspec,const GString *gstring,GValue *property_value);
gboolean    gtk_rc_property_parse_enum      (const GParamSpec *pspec,const GString *gstring,GValue *property_value);
gboolean    gtk_rc_property_parse_flags     (const GParamSpec *pspec,const GString *gstring,GValue *property_value);
gboolean    gtk_rc_property_parse_requisition(const GParamSpec *pspec,const GString *gstring,GValue *property_value);
gboolean    gtk_rc_property_parse_border    (const GParamSpec *pspec,const GString *gstring,GValue *property_value);
void        gtk_settings_set_property_value (GtkSettings *settings,const gchar *name,const GtkSettingsValue *svalue);
void        gtk_settings_set_string_property(GtkSettings *settings,const gchar *name,const gchar *v_string,const gchar *origin);
void        gtk_settings_set_long_property  (GtkSettings *settings,const gchar *name,glong v_long,const gchar *origin);
void        gtk_settings_set_double_property(GtkSettings *settings,const gchar *name,gdouble v_double,const gchar *origin);
