void        (*GtkPrintFunc)                 (gpointer func_data,const gchar *str);
gchar*      (*GtkTranslateFunc)             (const gchar *path,gpointer func_data);
void        (*GtkItemFactoryCallback)       ();
void        (*GtkItemFactoryCallback1)      (gpointer callback_data,guint callback_action,GtkWidget *widget);
void        (*GtkItemFactoryCallback2)      (GtkWidget *widget,gpointer callback_data,guint callback_action);
GtkItemFactory* gtk_item_factory_new        (GType container_type,const gchar *path,GtkAccelGroup *accel_group);
void        gtk_item_factory_construct      (GtkItemFactory *ifactory,GType container_type,const gchar *path,GtkAccelGroup *accel_group);
void        gtk_item_factory_add_foreign    (GtkWidget *accel_widget,const gchar *full_path,GtkAccelGroup *accel_group,guint keyval,GdkModifierType modifiers);
GtkItemFactory* gtk_item_factory_from_widget(GtkWidget *widget);
const gchar* gtk_item_factory_path_from_widget(GtkWidget *widget);
GtkWidget*  gtk_item_factory_get_item       (GtkItemFactory *ifactory,const gchar *path);
GtkWidget*  gtk_item_factory_get_widget     (GtkItemFactory *ifactory,const gchar *path);
GtkWidget*  gtk_item_factory_get_widget_by_action(GtkItemFactory *ifactory,guint action);
GtkWidget*  gtk_item_factory_get_item_by_action(GtkItemFactory *ifactory,guint action);
void        gtk_item_factory_create_item    (GtkItemFactory *ifactory,GtkItemFactoryEntry *entry,gpointer callback_data,guint callback_type);
void        gtk_item_factory_create_items   (GtkItemFactory *ifactory,guint n_entries,GtkItemFactoryEntry *entries,gpointer callback_data);
void        gtk_item_factory_create_items_ac(GtkItemFactory *ifactory,guint n_entries,GtkItemFactoryEntry *entries,gpointer callback_data,guint callback_type);
void        gtk_item_factory_delete_item    (GtkItemFactory *ifactory,const gchar *path);
void        gtk_item_factory_delete_entry   (GtkItemFactory *ifactory,GtkItemFactoryEntry *entry);
void        gtk_item_factory_delete_entries (GtkItemFactory *ifactory,guint n_entries,GtkItemFactoryEntry *entries);
void        gtk_item_factory_popup          (GtkItemFactory *ifactory,guint x,guint y,guint mouse_button,guint32 time_);
void        gtk_item_factory_popup_with_data(GtkItemFactory *ifactory,gpointer popup_data,GtkDestroyNotify destroy,guint x,guint y,guint mouse_button,guint32 time_);
gpointer    gtk_item_factory_popup_data     (GtkItemFactory *ifactory);
gpointer    gtk_item_factory_popup_data_from_widget(GtkWidget *widget);
GtkItemFactory* gtk_item_factory_from_path  (const gchar *path);
void        gtk_item_factory_create_menu_entries(guint n_entries,GtkMenuEntry *entries);
void        gtk_item_factories_path_delete  (const gchar *ifactory_path,const gchar *path);
void        gtk_item_factory_set_translate_func(GtkItemFactory *ifactory,GtkTranslateFunc func,gpointer data,GtkDestroyNotify notify);
