GtkWidget*  gtk_text_new                    (GtkAdjustment *hadj,GtkAdjustment *vadj);
void        gtk_text_set_editable           (GtkText *text,gboolean editable);
void        gtk_text_set_word_wrap          (GtkText *text,gboolean word_wrap);
void        gtk_text_set_line_wrap          (GtkText *text,gboolean line_wrap);
void        gtk_text_set_adjustments        (GtkText *text,GtkAdjustment *hadj,GtkAdjustment *vadj);
void        gtk_text_set_point              (GtkText *text,guint index);
guint       gtk_text_get_point              (GtkText *text);
guint       gtk_text_get_length             (GtkText *text);
void        gtk_text_freeze                 (GtkText *text);
void        gtk_text_thaw                   (GtkText *text);
void        gtk_text_insert                 (GtkText *text,GdkFont *font,const GdkColor *fore,const GdkColor *back,const char *chars,gint length);
gboolean    gtk_text_backward_delete        (GtkText *text,guint nchars);
gboolean    gtk_text_forward_delete         (GtkText *text,guint nchars);
