GtkIconTheme* gtk_icon_theme_new            (void);
GtkIconTheme* gtk_icon_theme_get_default    (void);
GtkIconTheme* gtk_icon_theme_get_for_screen (GdkScreen *screen);
void        gtk_icon_theme_set_screen       (GtkIconTheme *icon_theme,GdkScreen *screen);
void        gtk_icon_theme_set_search_path  (GtkIconTheme *icon_theme,const gchar *path[],gint n_elements);
void        gtk_icon_theme_get_search_path  (GtkIconTheme *icon_theme,gchar **path[],gint *n_elements);
void        gtk_icon_theme_append_search_path(GtkIconTheme *icon_theme,const gchar *path);
void        gtk_icon_theme_prepend_search_path(GtkIconTheme *icon_theme,const gchar *path);
void        gtk_icon_theme_set_custom_theme (GtkIconTheme *icon_theme,const gchar *theme_name);
gboolean    gtk_icon_theme_has_icon         (GtkIconTheme *icon_theme,const gchar *icon_name);
GtkIconInfo* gtk_icon_theme_lookup_icon     (GtkIconTheme *icon_theme,const gchar *icon_name,gint size,GtkIconLookupFlags flags);
GdkPixbuf*  gtk_icon_theme_load_icon        (GtkIconTheme *icon_theme,const gchar *icon_name,gint size,GtkIconLookupFlags flags,GError **error);
GList*      gtk_icon_theme_list_icons       (GtkIconTheme *icon_theme,const gchar *context);
gint*       gtk_icon_theme_get_icon_sizes   (GtkIconTheme *icon_theme,const gchar *icon_name);
char*       gtk_icon_theme_get_example_icon_name(GtkIconTheme *icon_theme);
gboolean    gtk_icon_theme_rescan_if_needed (GtkIconTheme *icon_theme);
void        gtk_icon_theme_add_builtin_icon (const gchar *icon_name,gint size,GdkPixbuf *pixbuf);
GtkIconInfo* gtk_icon_info_copy             (GtkIconInfo *icon_info);
void        gtk_icon_info_free              (GtkIconInfo *icon_info);
gint        gtk_icon_info_get_base_size     (GtkIconInfo *icon_info);
const gchar* gtk_icon_info_get_filename     (GtkIconInfo *icon_info);
GdkPixbuf*  gtk_icon_info_get_builtin_pixbuf(GtkIconInfo *icon_info);
GdkPixbuf*  gtk_icon_info_load_icon         (GtkIconInfo *icon_info,GError **error);
void        gtk_icon_info_set_raw_coordinates(GtkIconInfo *icon_info,gboolean raw_coordinates);
gboolean    gtk_icon_info_get_embedded_rect (GtkIconInfo *icon_info,GdkRectangle *rectangle);
gboolean    gtk_icon_info_get_attach_points (GtkIconInfo *icon_info,GdkPoint **points,gint *n_points);
const gchar* gtk_icon_info_get_display_name (GtkIconInfo *icon_info);
