#!/usr/bin/perl
print "genconf: Looking for mozilla-gtkmozembed... ";
my @output = qx(pkg-config --modversion mozilla-gtkmozembed 2> /dev/null);
my $mozpkg;
if ($? != 0) {
	print "not found\n";
	print "genconf: Looking for firefox-gtkmozembed... ";
	@output = qx(pkg-config --modversion firefox-gtkmozembed 2> /dev/null);
	if ($? != 0) {
		print "not found\n";
		print "genconf: Please install either the Firefox or the Mozilla development package.\n";
		exit 2;
	} else {
		$mozpkg = "firefox-gtkmozembed";
		print "found version " . $output[0];
	}
} else {
	$mozpkg = "mozilla-gtkmozembed";
	print "found version " . $output[0];
}
print "genconf: Running pkg-config\n";
if (!open(IN,"pkg-config --libs gtk+-2.0 gtk+-x11-2.0 glib-2.0 xcursor gthread-2.0 gmodule-2.0 libglade-2.0 xfixes gobject-2.0 vte $mozpkg |"))
{
	print "genconf: Couldn´t run pkg-config: $! $?\n";
	exit 1;
}

my $pkgval = <IN>;

if (!close(IN))
{
	print "genconf: Couldn´t close input stream: $! $?\n";
	exit 1;
}

my @spliced_output = split(/ /,$pkgval);
my $tval;

print "genconf: Opening binding.bmx\n";
if (!open(IN,"binding.bmx"))
{
	print "genconf: Couldn´t open binding.bmx: $! $?\n";
	exit 1;
}

print "genconf: Opening binding_new.bmx\n";
if (!open(OUT,">binding_new.bmx"))
{
	print "genconf: Couldn´t open binding_new.bmx for writing: $! $?\n";
	if (!close(IN))
	{
		print "genconf: Couldn´t close input stream: $! $?\n";
	}
	exit 1;
}

print "genconf: Processing\n";
my $line;
while($line = <IN>)
{
	if ($line eq "'STARTCONFIG\r\n")
	{
		while ($line = <IN>)
		{
			last if $line eq "'ENDCONFIG\r\n";
		}
		$line = "'INCLUDECONFIG\r\n";
	}

	if ($line eq "'INCLUDECONFIG\r\n")
	{
		print OUT "'STARTCONFIG\r\n";
		my $tval;
		foreach $tval (@spliced_output)
		{
			if ($tval ne "" && $tval ne "\n")
			{
				print OUT "Import \"" . $tval . "\"\r\n";
			}
		}
		print OUT "'ENDCONFIG\r\n";
	} else {
		print OUT $line;
	}
}

print "genconf: Closing streams\n";
if (!close(IN))
{
	print "genconf: Couldn´t close input stream: $! $?\n";
	if (!close(OUT))
	{
		print "genconf: Couldn´t close output stream: $! $?\n";
	}
	exit 1;
}
if (!close(OUT))
{
	print "genconf: Couldn´t close output stream: $! $?\n";
	exit 1;
}
