void        (*GtkTreeCellDataFunc)          (GtkTreeViewColumn *tree_column,GtkCellRenderer *cell,GtkTreeModel *tree_model,GtkTreeIter *iter,gpointer data);
GtkTreeViewColumn* gtk_tree_view_column_new (void);
GtkTreeViewColumn* gtk_tree_view_column_new_with_attributes(const gchar *title,GtkCellRenderer *cell,...);
void        gtk_tree_view_column_pack_start (GtkTreeViewColumn *tree_column,GtkCellRenderer *cell,gboolean expand);
void        gtk_tree_view_column_pack_end   (GtkTreeViewColumn *tree_column,GtkCellRenderer *cell,gboolean expand);
void        gtk_tree_view_column_clear      (GtkTreeViewColumn *tree_column);
GList*      gtk_tree_view_column_get_cell_renderers(GtkTreeViewColumn *tree_column);
void        gtk_tree_view_column_add_attribute(GtkTreeViewColumn *tree_column,GtkCellRenderer *cell_renderer,const gchar *attribute,gint column);
void        gtk_tree_view_column_set_attributes(GtkTreeViewColumn *tree_column,GtkCellRenderer *cell_renderer,...);
void        gtk_tree_view_column_set_cell_data_func(GtkTreeViewColumn *tree_column,GtkCellRenderer *cell_renderer,GtkTreeCellDataFunc func,gpointer func_data,GtkDestroyNotify destroy);
void        gtk_tree_view_column_clear_attributes(GtkTreeViewColumn *tree_column,GtkCellRenderer *cell_renderer);
void        gtk_tree_view_column_set_spacing(GtkTreeViewColumn *tree_column,gint spacing);
gint        gtk_tree_view_column_get_spacing(GtkTreeViewColumn *tree_column);
void        gtk_tree_view_column_set_visible(GtkTreeViewColumn *tree_column,gboolean visible);
gboolean    gtk_tree_view_column_get_visible(GtkTreeViewColumn *tree_column);
void        gtk_tree_view_column_set_resizable(GtkTreeViewColumn *tree_column,gboolean resizable);
gboolean    gtk_tree_view_column_get_resizable(GtkTreeViewColumn *tree_column);
void        gtk_tree_view_column_set_sizing (GtkTreeViewColumn *tree_column,GtkTreeViewColumnSizing type);
GtkTreeViewColumnSizing gtk_tree_view_column_get_sizing(GtkTreeViewColumn *tree_column);
gint        gtk_tree_view_column_get_width  (GtkTreeViewColumn *tree_column);
gint        gtk_tree_view_column_get_fixed_width(GtkTreeViewColumn *tree_column);
void        gtk_tree_view_column_set_fixed_width(GtkTreeViewColumn *tree_column,gint fixed_width);
void        gtk_tree_view_column_set_min_width(GtkTreeViewColumn *tree_column,gint min_width);
gint        gtk_tree_view_column_get_min_width(GtkTreeViewColumn *tree_column);
void        gtk_tree_view_column_set_max_width(GtkTreeViewColumn *tree_column,gint max_width);
gint        gtk_tree_view_column_get_max_width(GtkTreeViewColumn *tree_column);
void        gtk_tree_view_column_clicked    (GtkTreeViewColumn *tree_column);
void        gtk_tree_view_column_set_title  (GtkTreeViewColumn *tree_column,const gchar *title);
const gchar* gtk_tree_view_column_get_title (GtkTreeViewColumn *tree_column);
void        gtk_tree_view_column_set_expand (GtkTreeViewColumn *tree_column,gboolean expand);
gboolean    gtk_tree_view_column_get_expand (GtkTreeViewColumn *tree_column);
void        gtk_tree_view_column_set_clickable(GtkTreeViewColumn *tree_column,gboolean clickable);
gboolean    gtk_tree_view_column_get_clickable(GtkTreeViewColumn *tree_column);
void        gtk_tree_view_column_set_widget (GtkTreeViewColumn *tree_column,GtkWidget *widget);
GtkWidget*  gtk_tree_view_column_get_widget (GtkTreeViewColumn *tree_column);
void        gtk_tree_view_column_set_alignment(GtkTreeViewColumn *tree_column,gfloat xalign);
gfloat      gtk_tree_view_column_get_alignment(GtkTreeViewColumn *tree_column);
void        gtk_tree_view_column_set_reorderable(GtkTreeViewColumn *tree_column,gboolean reorderable);
gboolean    gtk_tree_view_column_get_reorderable(GtkTreeViewColumn *tree_column);
void        gtk_tree_view_column_set_sort_column_id(GtkTreeViewColumn *tree_column,gint sort_column_id);
gint        gtk_tree_view_column_get_sort_column_id(GtkTreeViewColumn *tree_column);
void        gtk_tree_view_column_set_sort_indicator(GtkTreeViewColumn *tree_column,gboolean setting);
gboolean    gtk_tree_view_column_get_sort_indicator(GtkTreeViewColumn *tree_column);
void        gtk_tree_view_column_set_sort_order(GtkTreeViewColumn *tree_column,GtkSortType order);
GtkSortType gtk_tree_view_column_get_sort_order(GtkTreeViewColumn *tree_column);
void        gtk_tree_view_column_cell_set_cell_data(GtkTreeViewColumn *tree_column,GtkTreeModel *tree_model,GtkTreeIter *iter,gboolean is_expander,gboolean is_expanded);
void        gtk_tree_view_column_cell_get_size(GtkTreeViewColumn *tree_column,GdkRectangle *cell_area,gint *x_offset,gint *y_offset,gint *width,gint *height);
gboolean    gtk_tree_view_column_cell_get_position(GtkTreeViewColumn *tree_column,GtkCellRenderer *cell_renderer,gint *start_pos,gint *width);
gboolean    gtk_tree_view_column_cell_is_visible(GtkTreeViewColumn *tree_column);
void        gtk_tree_view_column_focus_cell (GtkTreeViewColumn *tree_column,GtkCellRenderer *cell);
void        gtk_tree_view_column_queue_resize(GtkTreeViewColumn *tree_column);
