GtkWidget*  gtk_menu_item_new               (void);
GtkWidget*  gtk_menu_item_new_with_label    (const gchar *label);
GtkWidget*  gtk_menu_item_new_with_mnemonic (const gchar *label);
void        gtk_menu_item_set_right_justified(GtkMenuItem *menu_item,gboolean right_justified);
void        gtk_menu_item_set_submenu       (GtkMenuItem *menu_item,GtkWidget *submenu);
void        gtk_menu_item_set_accel_path    (GtkMenuItem *menu_item,const gchar *accel_path);
void        gtk_menu_item_remove_submenu    (GtkMenuItem *menu_item);
void        gtk_menu_item_select            (GtkMenuItem *menu_item);
void        gtk_menu_item_deselect          (GtkMenuItem *menu_item);
void        gtk_menu_item_activate          (GtkMenuItem *menu_item);
void        gtk_menu_item_toggle_size_request(GtkMenuItem *menu_item,gint *requisition);
void        gtk_menu_item_toggle_size_allocate(GtkMenuItem *menu_item,gint allocation);
gboolean    gtk_menu_item_get_right_justified(GtkMenuItem *menu_item);
GtkWidget*  gtk_menu_item_get_submenu       (GtkMenuItem *menu_item);
