void        gtk_spin_button_configure       (GtkSpinButton *spin_button,GtkAdjustment *adjustment,gdouble climb_rate,guint digits);
GtkWidget*  gtk_spin_button_new             (GtkAdjustment *adjustment,gdouble climb_rate,guint digits);
GtkWidget*  gtk_spin_button_new_with_range  (gdouble min,gdouble max,gdouble step);
void        gtk_spin_button_set_adjustment  (GtkSpinButton *spin_button,GtkAdjustment *adjustment);
GtkAdjustment* gtk_spin_button_get_adjustment(GtkSpinButton *spin_button);
void        gtk_spin_button_set_digits      (GtkSpinButton *spin_button,guint digits);
void        gtk_spin_button_set_increments  (GtkSpinButton *spin_button,gdouble step,gdouble page);
void        gtk_spin_button_set_range       (GtkSpinButton *spin_button,gdouble min,gdouble max);
gint        gtk_spin_button_get_value_as_int(GtkSpinButton *spin_button);
void        gtk_spin_button_set_value       (GtkSpinButton *spin_button,gdouble value);
void        gtk_spin_button_set_update_policy(GtkSpinButton *spin_button,GtkSpinButtonUpdatePolicy policy);
void        gtk_spin_button_set_numeric     (GtkSpinButton *spin_button,gboolean numeric);
void        gtk_spin_button_spin            (GtkSpinButton *spin_button,GtkSpinType direction,gdouble increment);
void        gtk_spin_button_set_wrap        (GtkSpinButton *spin_button,gboolean wrap);
void        gtk_spin_button_set_snap_to_ticks(GtkSpinButton *spin_button,gboolean snap_to_ticks);
void        gtk_spin_button_update          (GtkSpinButton *spin_button);
guint       gtk_spin_button_get_digits      (GtkSpinButton *spin_button);
void        gtk_spin_button_get_increments  (GtkSpinButton *spin_button,gdouble *step,gdouble *page);
gboolean    gtk_spin_button_get_numeric     (GtkSpinButton *spin_button);
void        gtk_spin_button_get_range       (GtkSpinButton *spin_button,gdouble *min,gdouble *max);
gboolean    gtk_spin_button_get_snap_to_ticks(GtkSpinButton *spin_button);
GtkSpinButtonUpdatePolicy gtk_spin_button_get_update_policy(GtkSpinButton *spin_button);
gdouble     gtk_spin_button_get_value       (GtkSpinButton *spin_button);
gboolean    gtk_spin_button_get_wrap        (GtkSpinButton *spin_button);
