void        gtk_container_add               (GtkContainer *container,GtkWidget *widget);
void        gtk_container_remove            (GtkContainer *container,GtkWidget *widget);
void        gtk_container_add_with_properties(GtkContainer *container,GtkWidget *widget,const gchar *first_prop_name,...);
GtkResizeMode gtk_container_get_resize_mode (GtkContainer *container);
void        gtk_container_set_resize_mode   (GtkContainer *container,GtkResizeMode resize_mode);
void        gtk_container_check_resize      (GtkContainer *container);
void        gtk_container_foreach           (GtkContainer *container,GtkCallback callback,gpointer callback_data);
void        gtk_container_foreach_full      (GtkContainer *container,GtkCallback callback,GtkCallbackMarshal marshal,gpointer callback_data,GtkDestroyNotify notify);
GList*      gtk_container_get_children      (GtkContainer *container);
void        gtk_container_set_reallocate_redraws(GtkContainer *container,gboolean needs_redraws);
void        gtk_container_set_focus_child   (GtkContainer *container,GtkWidget *child);
GtkAdjustment* gtk_container_get_focus_vadjustment(GtkContainer *container);
void        gtk_container_set_focus_vadjustment(GtkContainer *container,GtkAdjustment *adjustment);
GtkAdjustment* gtk_container_get_focus_hadjustment(GtkContainer *container);
void        gtk_container_set_focus_hadjustment(GtkContainer *container,GtkAdjustment *adjustment);
void        gtk_container_resize_children   (GtkContainer *container);
GType       gtk_container_child_type        (GtkContainer *container);
void        gtk_container_child_get         (GtkContainer *container,GtkWidget *child,const gchar *first_prop_name,...);
void        gtk_container_child_set         (GtkContainer *container,GtkWidget *child,const gchar *first_prop_name,...);
void        gtk_container_child_get_property(GtkContainer *container,GtkWidget *child,const gchar *property_name,GValue *value);
void        gtk_container_child_set_property(GtkContainer *container,GtkWidget *child,const gchar *property_name,const GValue *value);
void        gtk_container_child_get_valist  (GtkContainer *container,GtkWidget *child,const gchar *first_property_name,va_list var_args);
void        gtk_container_child_set_valist  (GtkContainer *container,GtkWidget *child,const gchar *first_property_name,va_list var_args);
void        gtk_container_forall            (GtkContainer *container,GtkCallback callback,gpointer callback_data);
guint       gtk_container_get_border_width  (GtkContainer *container);
void        gtk_container_set_border_width  (GtkContainer *container,guint border_width);
void        gtk_container_propagate_expose  (GtkContainer *container,GtkWidget *child,GdkEventExpose *event);
gboolean    gtk_container_get_focus_chain   (GtkContainer *container,GList **focusable_widgets);
void        gtk_container_set_focus_chain   (GtkContainer *container,GList *focusable_widgets);
void        gtk_container_unset_focus_chain (GtkContainer *container);
GParamSpec* gtk_container_class_find_child_property(GObjectClass *cclass,const gchar *property_name);
void        gtk_container_class_install_child_property(GtkContainerClass *cclass,guint property_id,GParamSpec *pspec);
GParamSpec** gtk_container_class_list_child_properties(GObjectClass *cclass,guint *n_properties);
