#!/bin/sh
echo "Automated installer for BlitzMax module Pub.GTK"
echo "(C) 2005-2006 by phiker"
echo "install: Checking identity"
if [ $LOGNAME = "root" ]; then
        echo "install: Installing as root can potentially cause problems, please install as normal user"
        exit 1
fi
echo "install: Configuring gtk.binding"
cd binding.mod
echo "install: Running perl config script"
./genconf
retval=$?
if [ $retval -ne 0 ]; then
        echo "install: genconf returned $retval, exiting"
        exit 1
fi
echo "install: Renaming files"
mv binding.bmx binding_old.bmx
retval=$?
if [ $retval -ne 0 ]; then
        echo "install: mv returned $retval, exiting"
        exit 1
fi
mv binding_new.bmx binding.bmx
retval=$?
if [ $retval -ne 0 ]; then
        echo "install: mv returned $retval, exiting"
        exit 1
fi
echo "install: Running bmk to make module"
../../../bin/bmk makemods gtk.binding
retval=$?
if [ $retval -ne 0 ]; then
        echo
        echo "install: bmk returned $retval, exiting"
        exit 1
fi
cd ..
echo "install: Configuring gtk.oop"
cd oop.mod
echo "install: Running bmk to make module"
../../../bin/bmk makemods gtk.oop
retval=$?
if [ $retval -ne 0 ]; then
	echo
	echo "install: bmk returned $retval, exiting"
	exit 1
fi
cd ..
echo "install: Configuring gtk.scintilla"
cd scintilla.mod
echo "install: Compiling Scintilla"
make -Cscintilla/gtk
retval=$?
if [ $retval -ne 0 ]; then
	echo "install: make returned $retval, exiting"
	exit 1
fi
echo "install: Configuring"
echo Import \"$(pwd)/scintilla/bin/scintilla.a\" > config.bmx
retval=$?
if [ $retval -ne 0 ]; then
	echo "install: echo returned $retval, exiting"
	exit 1
fi
echo "install: Running bmk to make module"
../../../bin/bmk makemods gtk.scintilla
retval=$?
if [ $retval -ne 0 ]; then
	echo
	echo "install: bmk returned $retval, exiting"
	exit 1
fi
cd ..
echo "install: Finished"
