GtkWidget*  gtk_toolbar_new                 (void);
void        gtk_toolbar_insert              (GtkToolbar *toolbar,GtkToolItem *item,gint pos);
gint        gtk_toolbar_get_item_index      (GtkToolbar *toolbar,GtkToolItem *item);
gint        gtk_toolbar_get_n_items         (GtkToolbar *toolbar);
GtkToolItem* gtk_toolbar_get_nth_item       (GtkToolbar *toolbar,gint n);
gint        gtk_toolbar_get_drop_index      (GtkToolbar *toolbar,gint x,gint y);
void        gtk_toolbar_set_drop_highlight_item(GtkToolbar *toolbar,GtkToolItem *tool_item,gint index_);
void        gtk_toolbar_set_show_arrow      (GtkToolbar *toolbar,gboolean show_arrow);
void        gtk_toolbar_set_orientation     (GtkToolbar *toolbar,GtkOrientation orientation);
void        gtk_toolbar_set_tooltips        (GtkToolbar *toolbar,gboolean enable);
void        gtk_toolbar_unset_icon_size     (GtkToolbar *toolbar);
gboolean    gtk_toolbar_get_show_arrow      (GtkToolbar *toolbar);
GtkOrientation gtk_toolbar_get_orientation  (GtkToolbar *toolbar);
GtkToolbarStyle gtk_toolbar_get_style       (GtkToolbar *toolbar);
GtkIconSize gtk_toolbar_get_icon_size       (GtkToolbar *toolbar);
gboolean    gtk_toolbar_get_tooltips        (GtkToolbar *toolbar);
GtkReliefStyle gtk_toolbar_get_relief_style (GtkToolbar *toolbar);
GtkWidget*  gtk_toolbar_append_item         (GtkToolbar *toolbar,const char *text,const char *tooltip_text,const char *tooltip_private_text,GtkWidget *icon,GtkSignalFunc callback,gpointer user_data);
GtkWidget*  gtk_toolbar_prepend_item        (GtkToolbar *toolbar,const char *text,const char *tooltip_text,const char *tooltip_private_text,GtkWidget *icon,GtkSignalFunc callback,gpointer user_data);
GtkWidget*  gtk_toolbar_insert_item         (GtkToolbar *toolbar,const char *text,const char *tooltip_text,const char *tooltip_private_text,GtkWidget *icon,GtkSignalFunc callback,gpointer user_data,gint position);
void        gtk_toolbar_append_space        (GtkToolbar *toolbar);
void        gtk_toolbar_prepend_space       (GtkToolbar *toolbar);
void        gtk_toolbar_insert_space        (GtkToolbar *toolbar,gint position);
GtkWidget*  gtk_toolbar_append_element      (GtkToolbar *toolbar,GtkToolbarChildType type,GtkWidget *widget,const char *text,const char *tooltip_text,const char *tooltip_private_text,GtkWidget *icon,GtkSignalFunc callback,gpointer user_data);
GtkWidget*  gtk_toolbar_prepend_element     (GtkToolbar *toolbar,GtkToolbarChildType type,GtkWidget *widget,const char *text,const char *tooltip_text,const char *tooltip_private_text,GtkWidget *icon,GtkSignalFunc callback,gpointer user_data);
GtkWidget*  gtk_toolbar_insert_element      (GtkToolbar *toolbar,GtkToolbarChildType type,GtkWidget *widget,const char *text,const char *tooltip_text,const char *tooltip_private_text,GtkWidget *icon,GtkSignalFunc callback,gpointer user_data,gint position);
void        gtk_toolbar_append_widget       (GtkToolbar *toolbar,GtkWidget *widget,const char *tooltip_text,const char *tooltip_private_text);
void        gtk_toolbar_prepend_widget      (GtkToolbar *toolbar,GtkWidget *widget,const char *tooltip_text,const char *tooltip_private_text);
void        gtk_toolbar_insert_widget       (GtkToolbar *toolbar,GtkWidget *widget,const char *tooltip_text,const char *tooltip_private_text,gint position);
void        gtk_toolbar_set_style           (GtkToolbar *toolbar,GtkToolbarStyle style);
GtkWidget*  gtk_toolbar_insert_stock        (GtkToolbar *toolbar,const gchar *stock_id,const char *tooltip_text,const char *tooltip_private_text,GtkSignalFunc callback,gpointer user_data,gint position);
void        gtk_toolbar_set_icon_size       (GtkToolbar *toolbar,GtkIconSize icon_size);
void        gtk_toolbar_remove_space        (GtkToolbar *toolbar,gint position);
void        gtk_toolbar_unset_style         (GtkToolbar *toolbar);
