GtkWidget*  gtk_font_button_new             (void);
GtkWidget*  gtk_font_button_new_with_font   (const gchar *fontname);
gboolean    gtk_font_button_set_font_name   (GtkFontButton *font_button,const gchar *fontname);
const gchar* gtk_font_button_get_font_name  (GtkFontButton *font_button);
void        gtk_font_button_set_show_style  (GtkFontButton *font_button,gboolean show_style);
gboolean    gtk_font_button_get_show_style  (GtkFontButton *font_button);
void        gtk_font_button_set_show_size   (GtkFontButton *font_button,gboolean show_size);
gboolean    gtk_font_button_get_show_size   (GtkFontButton *font_button);
void        gtk_font_button_set_use_font    (GtkFontButton *font_button,gboolean use_font);
gboolean    gtk_font_button_get_use_font    (GtkFontButton *font_button);
void        gtk_font_button_set_use_size    (GtkFontButton *font_button,gboolean use_size);
gboolean    gtk_font_button_get_use_size    (GtkFontButton *font_button);
void        gtk_font_button_set_title       (GtkFontButton *font_button,const gchar *title);
const gchar* gtk_font_button_get_title      (GtkFontButton *font_button);
